import React, { useMemo } from 'react';
import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { useCampusStore } from '../../stores/useCampusStore';
import { useThemeStore } from '../../stores/useThemeStore';

export const BLENDER_MODEL_PATH = '/models/jiet_campus_prototype.glb';

export const BlenderCampusModelContent: React.FC = () => {
  const activeFloorFilter = useCampusStore((state) => state.activeFloorFilter);
  const theme = useThemeStore((state) => state.theme);
  const isDark = theme === 'dark';

  // Load digital twin GLB generated by Blender
  const { scene } = useGLTF(BLENDER_MODEL_PATH);

  // Clone scene so materials and visibility can be adjusted safely per floor filter
  const clonedScene = useMemo(() => {
    const cloned = scene.clone(true);

    cloned.traverse((child: any) => {
      if (child.isMesh) {
        child.castShadow = true;
        child.receiveShadow = true;

        const name = child.name || '';
        const isFF = name.includes('FF_') || name.includes('_FF_') || name.includes('First_Floor');
        const isGF = name.includes('GF_') || name.includes('_GF_') || name.includes('Ground_Floor');

        // Floor visibility filter
        if (activeFloorFilter === 'ground') {
          if (isFF) {
            child.visible = false;
          } else {
            child.visible = true;
          }
        } else if (activeFloorFilter === 'first') {
          // In first floor mode, keep foundation plinth, pillars, courtyard, and stairs visible but hide GF room partitions & walls
          if (
            name.includes('GF_Exterior_Facade_Walls') ||
            name.includes('GF_Interior_Room_Partition_Walls') ||
            name.includes('Room_GF_') ||
            name.includes('GF_Corridor_Dividing_Walls_With_Doors') ||
            name.includes('GF_Partition_And_Door_Walls')
          ) {
            child.visible = false;
          } else {
            child.visible = true;
          }
        } else {
          // 'all' mode: everything is visible
          child.visible = true;
        }

        // Architectural material tuning for dark / light themes
        if (child.material) {
          if (Array.isArray(child.material)) {
            child.material.forEach((m: THREE.Material) => {
              if ('polygonOffset' in m) {
                (m as any).polygonOffset = true;
                (m as any).polygonOffsetFactor = 1;
                (m as any).polygonOffsetUnits = 1;
              }
            });
          } else {
            if ('polygonOffset' in child.material) {
              child.material.polygonOffset = true;
              child.material.polygonOffsetFactor = 1;
              child.material.polygonOffsetUnits = 1;
            }
          }
        }
      }
    });

    return cloned;
  }, [scene, activeFloorFilter, isDark]);

  return (
    <group
      name="blender-campus-model"
      position={[0, 0, 0]}
      scale={[1, 1, 1]}
      rotation={[0, 0, 0]}
    >
      <primitive object={clonedScene} />
    </group>
  );
};

// Safe wrapper with error boundary and suspense
export const BlenderCampusModel: React.FC = () => {
  return (
    <React.Suspense fallback={null}>
      <BlenderCampusModelContent />
    </React.Suspense>
  );
};

// Preload GLB for instant rendering in browser environments
if (typeof window !== 'undefined') {
  try {
    useGLTF.preload(BLENDER_MODEL_PATH);
  } catch {
    // Ignore preload in test environments
  }
}
